name: ARK Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  ARK-Pages-Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        
    - name: Install dependencies
      run: yarn --frozen-lockfile
      
    - name: Build website
      run: yarn build
    
    - name: Run Website
      run: yarn start
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: ark-all.github.io