name: ARK-Name-Check-unittest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ReactNameCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Init unit test
      run: |
        pip install pytest
        pip install pytest-xdist
    - name: Start ReactNameCheck
      run: |
        pytest -n auto .github/ActionPy/ReactNameCheck.py
      shell: bash