name: ARK Pages Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ARK-Pages-Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
    
    - name: Get yarn cache
      id: yarn-cache
      run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"
        
    - name: Install dependencies
      run: yarn --frozen-lockfile
      
    - name: Build website
      run: yarn build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.next
        cname: ark-all.github.io